db.casos.insertMany([
    {
        fecha_reporte: "6/3/2020 0:00:00",
        id_de_caso: 1,
        fecha_de_notificaci_n: "2/3/2020 0:00:00",
        departamento: 11,
        departamento_nom: "BOGOTA",
        ciudad_municipio: "11.001",
        ciudad_municipio_nom: "BOGOTA",
        edad: 19,
        unidad_medida: 1,
        sexo: "F",
        fuente_tipo_contagio: "Importado",
        ubicacion: "Casa",
        estado: "Leve",
        pais_viajo_1_cod: 380,
        pais_viajo_1_nom: "ITALIA",
        recuperado: "Recuperado",
        fecha_inicio_sintomas: "27/2/2020 0:00:00",
        fecha_muerte: "",
        fecha_diagnostico: "6/3/2020 0:00:00",
        fecha_recuperado: "13/3/2020 0:00:00",
        tipo_recuperacion: "PCR",
        per_etn_: 6,
        nom_grupo_: ""
    },{ 
        fecha_reporte: "9/3/2020 0:00:00",
        id_de_caso: 2,
        fecha_de_notificaci_n: "6/3/2020 0:00:00",
        departamento: 76,
        departamento_nom: "VALLE",
        ciudad_municipio: "76.111",
        ciudad_municipio_nom: "BUGA",
        edad: 34,
        unidad_medida: 1,
        sexo: "M",
        fuente_tipo_contagio: "Importado",
        ubicacion: "Casa",
        estado: "Leve",
        pais_viajo_1_cod: 724,
        pais_viajo_1_nom: "ESPAÑA",
        recuperado: "Recuperado",
        fecha_inicio_sintomas: "4/3/2020 0:00:00",
        fecha_muerte: "",
        fecha_diagnostico: "9/3/2020 0:00:00",
        fecha_recuperado: "19/3/2020 0:00:00",
        tipo_recuperacion: "PCR",
        per_etn_: 5,
        nom_grupo_: ""
    },{ 
        fecha_reporte: "9/3/2020 0:00:00",
        id_de_caso: 3,
        fecha_de_notificaci_n: "7/3/2020 0:00:00",
        departamento: 5,
        departamento_nom: "ANTIOQUIA",
        ciudad_municipio: "5.001",
        ciudad_municipio_nom: "MEDELLIN",
        edad: 50,
        unidad_medida: 1,
        sexo: "F",
        fuente_tipo_contagio: "Importado",
        ubicacion: "Casa",
        estado: "Leve",
        pais_viajo_1_cod: 724,
        pais_viajo_1_nom: "ESPAÑA",
        recuperado: "Recuperado",
        fecha_inicio_sintomas: "29/2/2020 0:00:00",
        fecha_muerte: "",
        fecha_diagnostico: "9/3/2020 0:00:00",
        fecha_recuperado: "15/3/2020 0:00:00",
        tipo_recuperacion: "PCR",
        per_etn_: 6,
        nom_grupo_: ""
    },{ 
        fecha_reporte: "11/3/2020 0:00:00",
        id_de_caso: 4,
        fecha_de_notificaci_n: "9/3/2020 0:00:00",
        departamento: 5,
        departamento_nom: "ANTIOQUIA",
        ciudad_municipio: "5.001",
        ciudad_municipio_nom: "MEDELLIN",
        edad: 55,
        unidad_medida: 1,
        sexo: "M",
        fuente_tipo_contagio: "Relacionado",
        ubicacion: "Casa",
        estado: "Leve",
        pais_viajo_1_cod: "",
        pais_viajo_1_nom: "",
        recuperado: "Recuperado",
        fecha_inicio_sintomas: "6/3/2020 0:00:00",
        fecha_muerte: "",
        fecha_diagnostico: "11/3/2020 0:00:00",
        fecha_recuperado: "26/3/2020 0:00:00",
        tipo_recuperacion: "PCR",
        per_etn_: 6,
        nom_grupo_: ""
    },{ 
        fecha_reporte: "11/3/2020 0:00:00",
        id_de_caso: 5,
        fecha_de_notificaci_n: "9/3/2020 0:00:00",
        departamento: 5,
        departamento_nom: "ANTIOQUIA",
        ciudad_municipio: "5.001",
        ciudad_municipio_nom: "MEDELLIN",
        edad: 25,
        unidad_medida: 1,
        sexo: "M",
        fuente_tipo_contagio: "Relacionado",
        ubicacion: "Casa",
        estado: "Leve",
        pais_viajo_1_cod: "",
        pais_viajo_1_nom: "",
        recuperado: "Recuperado",
        fecha_inicio_sintomas: "8/3/2020 0:00:00",
        fecha_muerte: "",
        fecha_diagnostico: "11/3/2020 0:00:00",
        fecha_recuperado: "23/3/2020 0:00:00",
        tipo_recuperacion: "PCR",
        per_etn_: 6,
        nom_grupo_: ""
    },{ 
        fecha_reporte: "11/3/2020 0:00:00",
        id_de_caso: 6,
        fecha_de_notificaci_n: "10/3/2020 0:00:00",
        departamento: 5,
        departamento_nom: "ANTIOQUIA",
        ciudad_municipio: "5.360",
        ciudad_municipio_nom: "ITAGUI",
        edad: 27,
        unidad_medida: 1,
        sexo: "F",
        fuente_tipo_contagio: "Relacionado",
        ubicacion: "Casa",
        estado: "Leve",
        pais_viajo_1_cod: "",
        pais_viajo_1_nom: "",
        recuperado: "Recuperado",
        fecha_inicio_sintomas: "6/3/2020 0:00:00",
        fecha_muerte: "",
        fecha_diagnostico: "11/3/2020 0:00:00",
        fecha_recuperado: "26/3/2020 0:00:00",
        tipo_recuperacion: "PCR",
        per_etn_: 6,
        nom_grupo_: ""
    },{ 
        fecha_reporte: "11/3/2020 0:00:00",
        id_de_caso: 7,
        fecha_de_notificaci_n: "8/3/2020 0:00:00",
        departamento: "13.001",
        departamento_nom: "CARTAGENA",
        ciudad_municipio: "13.001",
        ciudad_municipio_nom: "CARTAGENA",
        edad: 85,
        unidad_medida: 1,
        sexo: "F",
        fuente_tipo_contagio: "Importado",
        ubicacion: "Casa",
        estado: "Leve",
        pais_viajo_1_cod: "840",
        pais_viajo_1_nom: "ESTADOS UNIDOS DE AMÉRICA",
        recuperado: "Recuperado",
        fecha_inicio_sintomas: "2/3/2020 0:00:00",
        fecha_muerte: "",
        fecha_diagnostico: "11/3/2020 0:00:00",
        fecha_recuperado: "17/3/2020 0:00:00",
        tipo_recuperacion: "PCR",
        per_etn_: 6,
        nom_grupo_: ""
    },{ 
        fecha_reporte: "11/3/2020 0:00:00",
        id_de_caso: 8,
        fecha_de_notificaci_n: "9/3/2020 0:00:00",
        departamento: 11,
        departamento_nom: "BOGOTA",
        ciudad_municipio: "11.001",
        ciudad_municipio_nom: "BOGOTA",
        edad: 22,
        unidad_medida: 1,
        sexo: "F",
        fuente_tipo_contagio: "Importado",
        ubicacion: "Casa",
        estado: "Leve",
        pais_viajo_1_cod: 724,
        pais_viajo_1_nom: "ESPAÑA",
        recuperado: "Recuperado",
        fecha_inicio_sintomas: "6/3/2020 0:00:00",
        fecha_muerte: "",
        fecha_diagnostico: "11/3/2020 0:00:00",
        fecha_recuperado: "21/3/2020 0:00:00",
        tipo_recuperacion: "PCR",
        per_etn_: 6,
        nom_grupo_: ""
    },{ 
        fecha_reporte: "11/3/2020 0:00:00",
        id_de_caso: 9,
        fecha_de_notificaci_n: "8/3/2020 0:00:00",
        departamento: 11,
        departamento_nom: "BOGOTA",
        ciudad_municipio: "11.001",
        ciudad_municipio_nom: "BOGOTA",
        edad: 28,
        unidad_medida: 1,
        sexo: "F",
        fuente_tipo_contagio: "Importado",
        ubicacion: "Casa",
        estado: "Leve",
        pais_viajo_1_cod: 724,
        pais_viajo_1_nom: "ESPAÑA",
        recuperado: "Recuperado",
        fecha_inicio_sintomas: "7/3/2020 0:00:00",
        fecha_muerte: "",
        fecha_diagnostico: "11/3/2020 0:00:00",
        fecha_recuperado: "23/3/2020 0:00:00",
        tipo_recuperacion: "PCR",
        per_etn_: 6,
        nom_grupo_: ""
    },{ 
        fecha_reporte: "12/3/2020 0:00:00",
        id_de_caso: 10,
        fecha_de_notificaci_n: "12/3/2020 0:00:00",
        departamento: 11,
        departamento_nom: "BOGOTA",
        ciudad_municipio: "11.001",
        ciudad_municipio_nom: "BOGOTA",
        edad: 36,
        unidad_medida: 1,
        sexo: "F",
        fuente_tipo_contagio: "Importado",
        ubicacion: "Casa",
        estado: "Leve",
        pais_viajo_1_cod: 724,
        pais_viajo_1_nom: "ESPAÑA",
        recuperado: "Recuperado",
        fecha_inicio_sintomas: "6/3/2020 0:00:00",
        fecha_muerte: "",
        fecha_diagnostico: "12/3/2020 0:00:00",
        fecha_recuperado: "21/3/2020 0:00:00",
        tipo_recuperacion: "PCR",
        per_etn_: 6,
        nom_grupo_: ""
    },{ 
        fecha_reporte: "12/3/2020 0:00:00",
        id_de_caso: 11,
        fecha_de_notificaci_n: "11/3/2020 0:00:00",
        departamento: 11,
        departamento_nom: "BOGOTA",
        ciudad_municipio: "11.001",
        ciudad_municipio_nom: "BOGOTA",
        edad: 42,
        unidad_medida: 1,
        sexo: "F",
        fuente_tipo_contagio: "Importado",
        ubicacion: "Casa",
        estado: "Leve",
        pais_viajo_1_cod: 724,
        pais_viajo_1_nom: "ESPAÑA",
        recuperado: "Recuperado",
        fecha_inicio_sintomas: "6/3/2020 0:00:00",
        fecha_muerte: "",
        fecha_diagnostico: "12/3/2020 0:00:00",
        fecha_recuperado: "31/3/2020 0:00:00",
        tipo_recuperacion: "PCR",
        per_etn_: 6,
        nom_grupo_: ""
    },{ 
        fecha_reporte: "12/3/2020 0:00:00",
        id_de_caso: 12,
        fecha_de_notificaci_n: "10/3/2020 0:00:00",
        departamento: 41,
        departamento_nom: "HUILA",
        ciudad_municipio: "41.001",
        ciudad_municipio_nom: "NEIVA",
        edad: 74,
        unidad_medida: 1,
        sexo: "F",
        fuente_tipo_contagio: "Importado",
        ubicacion: "Casa",
        estado: "Leve",
        pais_viajo_1_cod: 380,
        pais_viajo_1_nom: "ITALIA",
        recuperado: "Recuperado",
        fecha_inicio_sintomas: "6/3/2020 0:00:00",
        fecha_muerte: "",
        fecha_diagnostico: "12/3/2020 0:00:00",
        fecha_recuperado: "9/4/2020 0:00:00",
        tipo_recuperacion: "PCR",
        per_etn_: 6,
        nom_grupo_: ""
    },{ 
        fecha_reporte: "12/3/2020 0:00:00",
        id_de_caso: 13,
        fecha_de_notificaci_n: "10/3/2020 0:00:00",
        departamento: 41,
        departamento_nom: "HUILA",
        ciudad_municipio: "41.001",
        ciudad_municipio_nom: "NEIVA",
        edad: 68,
        unidad_medida: 1,
        sexo: "F",
        fuente_tipo_contagio: "Relacionado",
        ubicacion: "Casa",
        estado: "Leve",
        pais_viajo_1_cod: "",
        pais_viajo_1_nom: "",
        recuperado: "Recuperado",
        fecha_inicio_sintomas: "6/3/2020 0:00:00",
        fecha_muerte: "",
        fecha_diagnostico: "12/3/2020 0:00:00",
        fecha_recuperado: "30/3/2020 0:00:00",
        tipo_recuperacion: "PCR",
        per_etn_: 6,
        nom_grupo_: ""
    },{ 
        fecha_reporte: "13/3/2020 0:00:00",
        id_de_caso: 14,
        fecha_de_notificaci_n: "10/3/2020 0:00:00",
        departamento: 76,
        departamento_nom: "VALLE",
        ciudad_municipio: "76.520",
        ciudad_municipio_nom: "PALMIRA",
        edad: 48,
        unidad_medida: 1,
        sexo: "M",
        fuente_tipo_contagio: "Importado",
        ubicacion: "Casa",
        estado: "Leve",
        pais_viajo_1_cod: 724,
        pais_viajo_1_nom: "ESPAÑA",
        recuperado: "Recuperado",
        fecha_inicio_sintomas: "7/3/2020 0:00:00",
        fecha_muerte: "",
        fecha_diagnostico: "13/3/2020 0:00:00",
        fecha_recuperado: "21/3/2020 0:00:00",
        tipo_recuperacion: "PCR",
        per_etn_: 5,
        nom_grupo_: ""
    },{ 
        fecha_reporte: "13/3/2020 0:00:00",
        id_de_caso: 15,
        fecha_de_notificaci_n: "13/3/2020 0:00:00",
        departamento: 50,
        departamento_nom: "META",
        ciudad_municipio: "50.001",
        ciudad_municipio_nom: "VILLAVICENCIO",
        edad: 30,
        unidad_medida: 1,
        sexo: "F",
        fuente_tipo_contagio: "Importado",
        ubicacion: "Casa",
        estado: "Leve",
        pais_viajo_1_cod: 724,
        pais_viajo_1_nom: "ESPAÑA",
        recuperado: "Recuperado",
        fecha_inicio_sintomas: "9/3/2020 0:00:00",
        fecha_muerte: "",
        fecha_diagnostico: "13/3/2020 0:00:00",
        fecha_recuperado: "23/3/2020 0:00:00",
        tipo_recuperacion: "PCR",
        per_etn_: 6,
        nom_grupo_: ""
    },{ 
        fecha_reporte: "13/3/2020 0:00:00",
        id_de_caso: 16,
        fecha_de_notificaci_n: "11/3/2020 0:00:00",
        departamento: 11,
        departamento_nom: "BOGOTA",
        ciudad_municipio: "11.001",
        ciudad_municipio_nom: "BOGOTA",
        edad: 61,
        unidad_medida: 1,
        sexo: "F",
        fuente_tipo_contagio: "Importado",
        ubicacion: "Casa",
        estado: "Leve",
        pais_viajo_1_cod: 380,
        pais_viajo_1_nom: "ITALIA",
        recuperado: "Recuperado",
        fecha_inicio_sintomas: "8/3/2020 0:00:00",
        fecha_muerte: "",
        fecha_diagnostico: "13/3/2020 0:00:00",
        fecha_recuperado: "23/3/2020 0:00:00",
        tipo_recuperacion: "PCR",
        per_etn_: 5,
        nom_grupo_: ""
    },{ 
        fecha_reporte: "14/3/2020 0:00:00",
        id_de_caso: 17,
        fecha_de_notificaci_n: "11/3/2020 0:00:00",
        departamento: 11,
        departamento_nom: "BOGOTA",
        ciudad_municipio: "11.001",
        ciudad_municipio_nom: "BOGOTA",
        edad: 73,
        unidad_medida: 1,
        sexo: "F",
        fuente_tipo_contagio: "Importado",
        ubicacion: "Casa",
        estado: "Leve",
        pais_viajo_1_cod: 724,
        pais_viajo_1_nom: "ESPAÑA",
        recuperado: "Recuperado",
        fecha_inicio_sintomas: "28/2/2020 0:00:00",
        fecha_muerte: "",
        fecha_diagnostico: "14/3/2020 0:00:00",
        fecha_recuperado: "14/3/2020 0:00:00",
        tipo_recuperacion: "PCR",
        per_etn_: 6,
        nom_grupo_: ""
    },{ 
        fecha_reporte: "14/3/2020 0:00:00",
        id_de_caso: 18,
        fecha_de_notificaci_n: "11/3/2020 0:00:00",
        departamento: 11,
        departamento_nom: "BOGOTA",
        ciudad_municipio: "11.001",
        ciudad_municipio_nom: "BOGOTA",
        edad: 54,
        unidad_medida: 1,
        sexo: "M",
        fuente_tipo_contagio: "Importado",
        ubicacion: "Casa",
        estado: "Leve",
        pais_viajo_1_cod: 724,
        pais_viajo_1_nom: "ESPAÑA",
        recuperado: "Recuperado",
        fecha_inicio_sintomas: "7/3/2020 0:00:00",
        fecha_muerte: "",
        fecha_diagnostico: "14/3/2020 0:00:00",
        fecha_recuperado: "7/4/2020 0:00:00",
        tipo_recuperacion: "Tiempo",
        per_etn_: 6,
        nom_grupo_: ""
    },{ 
        fecha_reporte: "14/3/2020 0:00:00",
        id_de_caso: 19,
        fecha_de_notificaci_n: "12/3/2020 0:00:00",
        departamento: 11,
        departamento_nom: "BOGOTA",
        ciudad_municipio: "11.001",
        ciudad_municipio_nom: "BOGOTA",
        edad: 54,
        unidad_medida: 1,
        sexo: "F",
        fuente_tipo_contagio: "Relacionado",
        ubicacion: "Casa",
        estado: "Leve",
        pais_viajo_1_cod: "",
        pais_viajo_1_nom: "",
        recuperado: "Recuperado",
        fecha_inicio_sintomas: "9/3/2020 0:00:00",
        fecha_muerte: "",
        fecha_diagnostico: "14/3/2020 0:00:00",
        fecha_recuperado: "24/3/2020 0:00:00",
        tipo_recuperacion: "PCR",
        per_etn_: 6,
        nom_grupo_: ""
    },{ 
        fecha_reporte: "14/3/2020 0:00:00",
        id_de_caso: 20,
        fecha_de_notificaci_n: "11/3/2020 0:00:00",
        departamento: 5,
        departamento_nom: "ANTIOQUIA",
        ciudad_municipio: "5.001",
        ciudad_municipio_nom: "MEDELLIN",
        edad: 26,
        unidad_medida: 1,
        sexo: "F",
        fuente_tipo_contagio: "Relacionado",
        ubicacion: "Casa",
        estado: "Leve",
        pais_viajo_1_cod: "",
        pais_viajo_1_nom: "",
        recuperado: "Recuperado",
        fecha_inicio_sintomas: "9/3/2020 0:00:00",
        fecha_muerte: "",
        fecha_diagnostico: "14/3/2020 0:00:00",
        fecha_recuperado: "24/3/2020 0:00:00",
        tipo_recuperacion: "PCR",
        per_etn_: 6,
        nom_grupo_: ""
    },{ 
        fecha_reporte: "14/3/2020 0:00:00",
        id_de_caso: 21,
        fecha_de_notificaci_n: "11/3/2020 0:00:00",
        departamento: 5,
        departamento_nom: "ANTIOQUIA",
        ciudad_municipio: "5.001",
        ciudad_municipio_nom: "MEDELLIN",
        edad: 28,
        unidad_medida: 1,
        sexo: "M",
        fuente_tipo_contagio: "Relacionado",
        ubicacion: "Casa",
        estado: "Leve",
        pais_viajo_1_cod: "",
        pais_viajo_1_nom: "",
        recuperado: "Recuperado",
        fecha_inicio_sintomas: "10/3/2020 0:00:00",
        fecha_muerte: "",
        fecha_diagnostico: "14/3/2020 0:00:00",
        fecha_recuperado: "10/4/2020 0:00:00",
        tipo_recuperacion: "PCR",
        per_etn_: 6,
        nom_grupo_: ""
    }
])